#ifndef IDAM_PLUGINS_PROVENANCE_LISTSIGNALS_H
#define IDAM_PLUGINS_PROVENANCE_LISTSIGNALS_H

#include <plugins/udaPlugin.h>

int listSignals(IDAM_PLUGIN_INTERFACE * idam_plugin_interface);

#endif // IDAM_PLUGINS_PROVENANCE_LISTSIGNALS_H
