#ifndef IDAM_PLUGINS_PROVENANCE_PUTSIGNAL_H
#define IDAM_PLUGINS_PROVENANCE_PUTSIGNAL_H

#include <idamplugin.h>

int putSignal(IDAM_PLUGIN_INTERFACE * idam_plugin_interface);

#endif // IDAM_PLUGINS_PROVENANCE_PUTSIGNAL_H