#ifndef UDA_SOURCE_CLIENT2_ERROR_CODES_H
#define UDA_SOURCE_CLIENT2_ERROR_CODES_H

#define NO_SOCKET_CONNECTION            (-10000)
#define PROBLEM_OPENING_LOGS            (-11000)
#define FILE_FORMAT_NOT_SUPPORTED       (-12000)
#define ERROR_ALLOCATING_DATA_BOCK_HEAP (-13000)
#define SERVER_BLOCK_ERROR              (-14000)
#define SERVER_SIDE_ERROR               (-14001)
#define DATA_BLOCK_RECEIPT_ERROR        (-15000)
#define ERROR_CONDITION_UNKNOWN         (-16000)

#endif //UDA_SOURCE_CLIENT2_ERROR_CODES_H
