MODULE mastCPF
DESCRIPTION Tools to Query the MAST CPF Database
VERSION 1.0
SOURCE David Muir (MAST)
BUILD_DATE 23 November 2010
FUNCTION  QUERYCPF   		3 3 KEYWORDS
FUNCTION  QUERYSTRCPF  		3 3 KEYWORDS
FUNCTION  QUERYARRAYCPF  	3 3 KEYWORDS
FUNCTION  QUERYSINGLEARRAYCPF  	3 3 KEYWORDS
FUNCTION  COUNTCPF  		3 3 KEYWORDS
FUNCTION  GROUPCOUNTCPF  	3 3 KEYWORDS
FUNCTION  PUTCPF     		4 4 KEYWORDS
FUNCTION  KILLCPF    		2 2 KEYWORDS
FUNCTION  CLOSECPF    		0 0  

