set( UDA_HOST localhost )
set( UDA_PORT 56565 )

add_definitions(
  -DUDA_SERVER_HOST="localhost"
  -DUDA_SERVER_HOST2=""
  -DUDA_SERVER_PORT=56565
  -DUDA_SERVER_PORT2=56565
  -DAPI_DEVICE="JET"
  -DAPI_ARCHIVE="JET"
  -DAPI_PARSE_STRING="::"
  -DAPI_FILE_FORMAT="ppf"
  -DDEFAULT_ARCHIVE_DIR=""
  -DLOCAL_MDSPLUS_SERVER=""
  -DMAST_STARTPULSE=1
  -DFORMAT_LEGACY="PPF"
  -DFORMAT_MODERN="PPF"
  -DSQL_PORT=56566
  -DSQL_DBNAME="idam"
  -DSQL_USER="readonly"
  -DSQL_HOST="localhost"
  -DJETSERVER=1
  -DNOTGENERICENABLED=1
)
