set( UDA_HOST localhost )
set( UDA_PORT 56565 )

add_definitions(
  -DUDA_SERVER_HOST="localhost"
  -DUDA_SERVER_HOST2=""
  -DUDA_SERVER_PORT=56564
  -DUDA_SERVER_PORT2=0
  -DAPI_DEVICE="ITER"
  -DAPI_ARCHIVE="ITER"
  -DAPI_PARSE_STRING="::"
  -DAPI_FILE_FORMAT=""
  -DDEFAULT_ARCHIVE_DIR="/net/fuslsa/data/MAST_Data/"
  -DLOCAL_MDSPLUS_SERVER="idam0"
  -DMAST_STARTPULSE=12270
  -DFORMAT_LEGACY="IDA3"
  -DFORMAT_MODERN="CDF"
  -DSQL_PORT=56566
  -DSQL_DBNAME="idam"
  -DSQL_USER="readonly"
  -DSQL_HOST="idam1"
)