FROM ubuntu:24.04

ARG UDA_VERSION="main"
ARG SSL_AUTH="ON"
ARG CAPNP="ON"
ARG CLIENT_ONLY="OFF"
ARG INSTALL_DIR="/usr"
ARG BUILD_CORES=4

RUN apt-get update && apt-get install -y \
    git \
    libboost-dev \
    libboost-program-options-dev \
    libssl-dev \
    cmake \
    build-essential \
    libtirpc-dev \
    pkg-config \
    libxml2-dev \
    libspdlog-dev \
    ninja-build \
    capnproto \
    libcapnp-dev \
    lintian && \
    sed -i 's/if (yes)  # WITH_LIBATOMIC/if (no)  # WITH_LIBATOMIC/' \
    /usr/lib/x86_64-linux-gnu/cmake/CapnProto/CapnProtoConfig.cmake


RUN git clone https://github.com/ukaea/UDA.git /uda && \
    git -C /uda checkout "$UDA_VERSION"

RUN cd /uda && \
    cmake -B build \
    -DBUILD_SHARED_LIBS=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DSSLAUTHENTICATION="$SSL_AUTH" \
    -DCLIENT_ONLY="$CLIENT_ONLY" \
    -DENABLE_CAPNP="$CAPNP" \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR"

RUN cd /uda && cmake --build build -j "$BUILD_CORES" --config Release --target install
RUN cd /uda && cmake --build build --target package
RUN lintian --fail-on error /uda/build/*.deb
