#!/bin/bash

#--------------------------------------------------------------------------
# Print the Certificate's Contents

TYPE=${1:-CLIENT}	# CAROOT, SERVER 
ROOT=${2:-$HOME/.UDA} 

TARGET=${ROOT}/client/clientX509.pem

if [ ${TYPE} = CAROOT ]; then
   TARGET=${ROOT}/caroot/certs/carootX509.pem
fi

if [ ${TYPE} = SERVER ]; then
   TARGET=${ROOT}/server/serverX509.pem
fi

#openssl x509 -in $TARGET -noout -text
#exit

openssl x509 -in $TARGET -noout -subject_hash
openssl x509 -in $TARGET -noout -issuer_hash

openssl x509 -md5  -in $TARGET -noout -fingerprint
openssl x509 -sha1 -in $TARGET -noout -fingerprint

echo "========================================================="

openssl x509 -in $TARGET -noout -text
openssl x509 -in $TARGET -noout -serial
openssl x509 -in $TARGET -noout -issuer
openssl x509 -in $TARGET -noout -subject
openssl x509 -in $TARGET -noout -subject -nameopt RFC2253
openssl x509 -in $TARGET -noout -purpose

echo "========================================================="

openssl x509 -in $TARGET -noout -pubkey
openssl x509 -in $TARGET -noout -modulus
openssl x509 -in $TARGET -noout -startdate
openssl x509 -in $TARGET -noout -enddate
openssl x509 -in $TARGET -noout -dates

#openssl x509 -in $TARGET -noout -C

exit

# CN common name
# OU organisational unit
# O organisation
# L location
# ST State of residence
# C country of residence
# EMAILADDRESS
# rfc822Name 
