#!/bin/bash

module purge
module load idl/08.3
module load mdsplus/6.1
module load java/1.8

export HDF5_USE_SHLIB=yes

/home/jholloc/freia/bin/cmake -Bbuild_freia -H. -DCMAKE_BUILD_TYPE=Debug -DTARGET_TYPE=MAST \
    -DCMAKE_INSTALL_PREFIX=/home/jholloc/freia \
    -DSWIG_DIR=/home/jholloc/freia/bin \
    -DUDUNITS_ROOT=/home/jholloc/freia \
    -DPYTHON_INCLUDE_DIR=/usr/local/depot/Python-3.3.5/include/python3.3m/ -DPYTHON_LIBRARY=/usr/local/depot/Python-3.3.5/lib/libpython3.3m.so \
    $*

#-DIMAS_ROOT=$HOME/Projects/CPT/installer_hdf5/src/master/3/UAL \
    #-DMDSPLUS_DIR=/usr/local/depot/mdsplus-5.0 \
