#!/bin/bash

module purge
module load idl/08.4
module load mdsplus/6.1
module load java/1.8
module load udunits/2.2.24
module load python/3.3.5

export HDF5_USE_SHLIB=yes
export BOOST_ROOT=/usr/local/depot/boost-1.60

VERSION=`git describe --always --dirty --tags`

cmake -Bbuild_freia -H. -DCMAKE_BUILD_TYPE=Debug -DTARGET_TYPE=MAST \
    -DCMAKE_INSTALL_PREFIX=$HOME/freia/uda/$VERSION \
    -DSWIG_EXECUTABLE=/home/jholloc/freia/bin/swig \
    -DUDUNITS_ROOT=$UDUNITS_DIR \
    -DPYTHON_EXECUTABLE=$(which python3)
    $*

#    -DCLIENT_ONLY=TRUE \

#    -DCMAKE_INSTALL_PREFIX=/common/IMAS/extra/uda/$VERSION \
#-DIMAS_ROOT=$HOME/Projects/CPT/installer_hdf5/src/master/3/UAL \
    #-DMDSPLUS_DIR=/usr/local/depot/mdsplus-5.0 \
