#!/bin/bash

#------------------------------------------------------------------------------------------------
#  Script to Run AWS S3 example code
#------------------------------------------------------------------------------------------------

module purge
module load use.own aws3

mkdir -p /tmp/uda/s3

#ldd ./create_bucket

#./create_bucket dgmbucket
#./list_buckets

#./put_object dgmbucket qwerty /home/localadmin/out 
#./list_objects dgmbucket qwerty /home/localadmin/out

./get_object dgmbucket qwerty 
 

exit

r=getdata("aws::get(bucket=dgmbucket, object=qwerty)","")
