function( snake_to_proper_case input out_var )
  string( REPLACE "_" ";" tokens "${input}" )
  set( ${out_var} "" )
  foreach( token ${tokens} )
    string( SUBSTRING ${token} 0 1 first_char )
    string( SUBSTRING ${token} 1 -1 remainder )
    string( TOUPPER ${first_char} upper_first_char )
    string( TOLOWER ${remainder} lower_remainder )
    set( new_token "${upper_first_char}${lower_remainder}" )
    string( APPEND ${out_var} ${new_token} )
  endforeach(  )
  return( PROPAGATE ${out_var} )
endfunction( snake_to_proper_case )