name: Build binary distributions

on:
  push:
    branches: 
      - develop
      - main 
      - 'feature/**'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        distro:
          - rocky8
          # - manylinux2_28

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: get version
        id: version
        run: |
          VERSION=`git describe --tags`
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build image for ${{ matrix.distro }}
        run: |
          docker build \
            --build-arg UDA_VERSION=${{ github.sha }} \
            -f docker/Dockerfile.${{ matrix.distro }} \
            -t uda-${{ matrix.distro }}:${{ steps.version.outputs.version }} .

      - name: Run container
        run: |
          mkdir -p build_artifacts/${{ matrix.distro }}/bin
          mkdir -p build_artifacts/${{ matrix.distro }}/pkg
          id=`docker create uda-${{ matrix.distro }}:${{ steps.version.outputs.version }}`
          docker cp $id:/uda/install build_artifacts/${{ matrix.distro }}/bin
          docker cp $id:/uda/build/*.deb build_artifacts/${{ matrix.distro }}/pkg || true
          docker cp $id:/uda/build/*.rpm build_artifacts/${{ matrix.distro }}/pkg || true
          docker cp $id:/uda/build/*.tar.gz build_artifacts/${{ matrix.distro }}/pkg || true
          docker rm $id

      - name: Upload binaries for ${{ matrix.distro }}
        uses: actions/upload-artifact@v4
        with:
          name: uda-${{ steps.version.outputs.version }}-${{ matrix.distro }}
          path: build_artifacts/${{ matrix.distro }}/bin
          retention-days: ${{ github.ref_type == 'tag' && 365 || 7 }}

      - name: Upload linux packages for ${{ matrix.distro }}
        uses: actions/upload-artifact@v4
        with:
          name: uda-${{ steps.version.outputs.version }}-${{ matrix.distro }}
          path: build_artifacts/${{ matrix.distro }}/pkg
          retention-days: ${{ github.ref_type == 'tag' && 365 || 7 }}

